"""SQLAlchemy table mappings kept separate from domain contracts."""

from datetime import datetime
from typing import Any

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import JSON, Uuid

JSONB = JSON().with_variant(postgresql.JSONB(), "postgresql")
"""JSONB on CockroachDB and PostgreSQL; portable JSON elsewhere for tests."""

UUID_STR = Uuid(as_uuid=False)
"""Native UUID column mapped to ``str`` in Python.

Identifiers are generated by the application. Autoincrement integer keys are
avoided because sequential insertion creates range hotspots in a distributed
cluster (ADR-0005).
"""


class Base(DeclarativeBase):
    """Base for KAE-Memory relational mappings."""


class KnowledgeItemRow(Base):
    """Current lifecycle and identity for a durable knowledge item."""

    __tablename__ = "knowledge_items"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    kind: Mapped[str] = mapped_column(String(80), nullable=False)
    lifecycle: Mapped[str] = mapped_column(String(32), nullable=False)


class KnowledgeVersionRow(Base):
    """Append-only content and provenance for one knowledge version."""

    __tablename__ = "knowledge_versions"
    __table_args__ = (UniqueConstraint("knowledge_item_id", "version_number"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    knowledge_item_id: Mapped[str] = mapped_column(
        ForeignKey("knowledge_items.id", ondelete="CASCADE"), nullable=False, index=True
    )
    version_number: Mapped[int] = mapped_column(Integer, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    actor_id: Mapped[str] = mapped_column(String(64), nullable=False)
    execution_id: Mapped[str] = mapped_column(String(64), nullable=False)
    recorded_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ProjectRow(Base):
    """Durable aggregate boundary."""

    __tablename__ = "projects"

    project_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_key: Mapped[str] = mapped_column(String(120), nullable=False, unique=True)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class SessionRow(Base):
    """User-facing working session within a project."""

    __tablename__ = "sessions"
    __table_args__ = (Index("ix_sessions_project_started", "project_id", "started_at"),)

    session_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    session_type: Mapped[str] = mapped_column(String(32), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class AgentRunRow(Base):
    """Durable record of one agent execution.

    This table records that an execution happened. It never owns knowledge.
    """

    __tablename__ = "agent_runs"
    __table_args__ = (
        UniqueConstraint("project_id", "idempotency_key", "attempt_number"),
        Index("ix_agent_runs_project_created", "project_id", "created_at"),
        Index("ix_agent_runs_project_status", "project_id", "status"),
        Index("ix_agent_runs_session_created", "session_id", "created_at"),
    )

    agent_run_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    session_id: Mapped[str | None] = mapped_column(
        UUID_STR, ForeignKey("sessions.session_id"), nullable=True
    )
    agent_role: Mapped[str] = mapped_column(String(32), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    idempotency_key: Mapped[str] = mapped_column(String(200), nullable=False)
    attempt_number: Mapped[int] = mapped_column(BigInteger, nullable=False, default=1)
    input_context: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    output_summary: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    continuation_state: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    failed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    error_code: Mapped[str | None] = mapped_column(String(80), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class MessageRow(Base):
    """Immutable interaction evidence."""

    __tablename__ = "messages"
    __table_args__ = (
        UniqueConstraint("session_id", "sequence_number"),
        Index("ix_messages_session_sequence", "session_id", "sequence_number"),
        Index("ix_messages_project_created", "project_id", "created_at"),
    )

    message_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    session_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("sessions.session_id"), nullable=False
    )
    agent_run_id: Mapped[str | None] = mapped_column(
        UUID_STR, ForeignKey("agent_runs.agent_run_id"), nullable=True
    )
    sequence_number: Mapped[int] = mapped_column(BigInteger, nullable=False)
    actor_type: Mapped[str] = mapped_column(String(32), nullable=False)
    actor_id: Mapped[str | None] = mapped_column(String(120), nullable=True)
    message_type: Mapped[str] = mapped_column(String(40), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    message_metadata: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, nullable=False, default=dict
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class KnowledgeRelationshipRow(Base):
    """Directed, typed edge between two knowledge items.

    Endpoints are ``String(64)`` because revision 0001 created
    ``knowledge_items.id`` as ``String(64)``, not a UUID column.
    """

    __tablename__ = "knowledge_relationships"
    __table_args__ = (
        UniqueConstraint(
            "source_knowledge_item_id", "target_knowledge_item_id", "relationship_type"
        ),
        CheckConstraint(
            "source_knowledge_item_id <> target_knowledge_item_id",
            name="ck_knowledge_relationships_distinct_endpoints",
        ),
        Index(
            "ix_knowledge_relationships_project_source", "project_id", "source_knowledge_item_id"
        ),
        Index(
            "ix_knowledge_relationships_project_target", "project_id", "target_knowledge_item_id"
        ),
    )

    relationship_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    source_knowledge_item_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("knowledge_items.id"), nullable=False
    )
    target_knowledge_item_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("knowledge_items.id"), nullable=False
    )
    relationship_type: Mapped[str] = mapped_column(String(40), nullable=False)
    created_by_agent_run_id: Mapped[str | None] = mapped_column(
        UUID_STR, ForeignKey("agent_runs.agent_run_id"), nullable=True
    )
    relationship_metadata: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, nullable=False, default=dict
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ProvenanceLinkRow(Base):
    """Relational link from knowledge to the run or message it came from.

    Keyed by ``(knowledge_item_id, knowledge_version_number)`` rather than a
    foreign key onto ``knowledge_versions.id``, so revision 0001 stays unchanged.
    """

    __tablename__ = "knowledge_provenance_links"
    __table_args__ = (
        Index("ix_provenance_links_item_type", "knowledge_item_id", "link_type"),
        Index("ix_provenance_links_agent_run", "agent_run_id"),
    )

    provenance_link_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    knowledge_item_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("knowledge_items.id"), nullable=False
    )
    knowledge_version_number: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    agent_run_id: Mapped[str | None] = mapped_column(
        UUID_STR, ForeignKey("agent_runs.agent_run_id"), nullable=True
    )
    message_id: Mapped[str | None] = mapped_column(
        UUID_STR, ForeignKey("messages.message_id"), nullable=True
    )
    link_type: Mapped[str] = mapped_column(String(40), nullable=False)
    source_type: Mapped[str | None] = mapped_column(String(40), nullable=True)
    source_reference: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
