"""SQLAlchemy table mappings kept separate from domain contracts."""

from datetime import datetime
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import UserDefinedType, Uuid

from kae_memory.persistence import providers
from kae_memory.persistence.providers import ProviderAdapter

JSONB = postgresql.JSONB()
"""Native JSONB.

Provider-specific DDL is resolved through the configured provider adapter, not
hardcoded here (ADR-0022)."""


def _active_adapter() -> ProviderAdapter:
    """Return the configured provider's adapter.

    Resolved when the DDL is compiled rather than at import, so a process can be
    configured before its schema is described — and so importing the mapping
    never requires a database to be configured at all, which the migration
    tooling and the unit tests both rely on.

    Falls back to CockroachDB only when nothing is configured, because a bare
    import must not fail; a real deployment resolves explicitly and a missing
    provider is refused at startup.
    """

    try:
        return providers.resolve().adapter
    except providers.ProviderConfigurationError:
        return providers.adapter_for(providers.DatabaseProvider.COCKROACHDB)


class Vector(UserDefinedType[Any]):
    """A fixed-dimension vector column, compiled per provider.

    A user-defined type rather than a dialect type: SQLAlchemy has no built-in
    mapping for either CockroachDB's native vector or pgvector's. The DDL comes
    from the configured provider adapter, so the mapping below stays one
    declaration rather than two schemas that must be kept in step.

    The wire format is the same on both — values cross as the ``'[1,2,3]'``
    literal and come back as a string the repository parses — which is why only
    the column spec varies.
    """

    cache_ok = True

    def __init__(self, dimensions: int, adapter: ProviderAdapter | None = None) -> None:
        self.dimensions = dimensions
        self._adapter = adapter

    def get_col_spec(self, **_: Any) -> str:
        adapter = self._adapter or _active_adapter()
        return adapter.vector_column_spec(self.dimensions)

    def bind_processor(self, dialect: Any) -> Any:
        def process(value: Any) -> Any:
            if value is None:
                return None
            return "[" + ",".join(repr(float(component)) for component in value) + "]"

        return process


UUID_STR = Uuid(as_uuid=False)
"""Native UUID column mapped to ``str`` in Python.

Identifiers are generated by the application. Autoincrement integer keys are
avoided because sequential insertion creates range hotspots in a distributed
cluster (ADR-0005).
"""


class Base(DeclarativeBase):
    """Base for KAE-Memory relational mappings."""


class KnowledgeItemRow(Base):
    """Current lifecycle and identity for a durable knowledge item."""

    __tablename__ = "knowledge_items"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    kind: Mapped[str] = mapped_column(String(80), nullable=False)
    lifecycle: Mapped[str] = mapped_column(String(32), nullable=False)


class KnowledgeVersionRow(Base):
    """Append-only content and provenance for one knowledge version."""

    __tablename__ = "knowledge_versions"
    __table_args__ = (UniqueConstraint("knowledge_item_id", "version_number"),)

    #: 64-bit deliberately. ``Integer`` compiles to a 32-bit column on
    #: PostgreSQL and a 64-bit one on CockroachDB, whose INT is INT8 — so the
    #: same migration produced two different schemas, and CockroachDB's
    #: ``unique_rowid()`` values do not fit in the narrower one.
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    knowledge_item_id: Mapped[str] = mapped_column(
        ForeignKey("knowledge_items.id", ondelete="CASCADE"), nullable=False, index=True
    )
    #: 64-bit for the same reason as ``id``: ``Integer`` realises as 32 bits on
    #: PostgreSQL and 64 on CockroachDB, so a bare one leaves the two providers
    #: holding different schemas. Version numbers are small — the width is not
    #: the point, agreeing on it is.
    version_number: Mapped[int] = mapped_column(BigInteger, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    actor_id: Mapped[str] = mapped_column(String(64), nullable=False)
    execution_id: Mapped[str] = mapped_column(String(64), nullable=False)
    recorded_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ProjectRow(Base):
    """Durable aggregate boundary."""

    __tablename__ = "projects"

    project_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_key: Mapped[str] = mapped_column(String(120), nullable=False, unique=True)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Monotonic counter incremented on every authoritative knowledge change. A
    # counter rather than a timestamp: timestamps collide under concurrent writes
    # and make "did anything change since this snapshot?" ambiguous (ADR-0012).
    knowledge_revision: Mapped[int] = mapped_column(BigInteger, nullable=False, default=0)


class SessionRow(Base):
    """User-facing working session within a project."""

    __tablename__ = "sessions"
    __table_args__ = (Index("ix_sessions_project_started", "project_id", "started_at"),)

    session_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    session_type: Mapped[str] = mapped_column(String(32), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class AgentRunRow(Base):
    """Durable record of one agent execution.

    This table records that an execution happened. It never owns knowledge.
    """

    __tablename__ = "agent_runs"
    __table_args__ = (
        UniqueConstraint("project_id", "idempotency_key", "attempt_number"),
        Index("ix_agent_runs_project_created", "project_id", "created_at"),
        Index("ix_agent_runs_project_status", "project_id", "status"),
        Index("ix_agent_runs_session_created", "session_id", "created_at"),
        Index("ix_agent_runs_claimable", "status", "next_attempt_at"),
    )

    agent_run_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    session_id: Mapped[str | None] = mapped_column(
        UUID_STR, ForeignKey("sessions.session_id"), nullable=True
    )
    agent_role: Mapped[str] = mapped_column(String(32), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    idempotency_key: Mapped[str] = mapped_column(String(200), nullable=False)
    attempt_number: Mapped[int] = mapped_column(BigInteger, nullable=False, default=1)
    input_context: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    output_summary: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    continuation_state: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    failed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    error_code: Mapped[str | None] = mapped_column(String(80), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Lease ownership (revision 0003, ADR-0007). The claim is committed state,
    # not a held lock: CockroachDB row locks do not outlive their transaction, so
    # a long model call cannot be protected by keeping SELECT FOR UPDATE open.
    lease_owner: Mapped[str | None] = mapped_column(String(120), nullable=True)
    lease_token: Mapped[int] = mapped_column(BigInteger, nullable=False, default=0)
    lease_acquired_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    lease_expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    heartbeat_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    next_attempt_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class MessageRow(Base):
    """Immutable interaction evidence."""

    __tablename__ = "messages"
    __table_args__ = (
        UniqueConstraint("session_id", "sequence_number"),
        # Idempotency is enforced here, not by a read-then-insert: a lookup
        # before an insert races, and the guarantee has to survive two clients
        # and a crash between the two statements (ADR-0018).
        UniqueConstraint("project_id", "idempotency_key", name="uq_messages_project_idempotency"),
        Index("ix_messages_session_sequence", "session_id", "sequence_number"),
        Index("ix_messages_project_created", "project_id", "created_at"),
    )

    message_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    session_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("sessions.session_id"), nullable=False
    )
    agent_run_id: Mapped[str | None] = mapped_column(
        UUID_STR, ForeignKey("agent_runs.agent_run_id"), nullable=True
    )
    sequence_number: Mapped[int] = mapped_column(BigInteger, nullable=False)
    actor_type: Mapped[str] = mapped_column(String(32), nullable=False)
    actor_id: Mapped[str | None] = mapped_column(String(120), nullable=True)
    message_type: Mapped[str] = mapped_column(String(40), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    message_metadata: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, nullable=False, default=dict
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    idempotency_key: Mapped[str | None] = mapped_column(String(200), nullable=True)
    #: SHA-256 over the normalised payload. Sameness is decided by comparing
    #: this, never by comparing free text.
    payload_fingerprint: Mapped[str | None] = mapped_column(String(64), nullable=True)
    #: What the caller declared this message was for (EM-2). NULL on every row
    #: written before the column existed, and read as `project_input` — which
    #: is what those messages were.
    purpose: Mapped[str | None] = mapped_column(String(40), nullable=True)


class KnowledgeRelationshipRow(Base):
    """Directed, typed edge between two knowledge items.

    Endpoints are ``String(64)`` because revision 0001 created
    ``knowledge_items.id`` as ``String(64)``, not a UUID column.
    """

    __tablename__ = "knowledge_relationships"
    __table_args__ = (
        UniqueConstraint(
            "source_knowledge_item_id", "target_knowledge_item_id", "relationship_type"
        ),
        CheckConstraint(
            "source_knowledge_item_id <> target_knowledge_item_id",
            name="ck_knowledge_relationships_distinct_endpoints",
        ),
        Index(
            "ix_knowledge_relationships_project_source", "project_id", "source_knowledge_item_id"
        ),
        Index(
            "ix_knowledge_relationships_project_target", "project_id", "target_knowledge_item_id"
        ),
    )

    relationship_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    source_knowledge_item_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("knowledge_items.id"), nullable=False
    )
    target_knowledge_item_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("knowledge_items.id"), nullable=False
    )
    relationship_type: Mapped[str] = mapped_column(String(40), nullable=False)
    created_by_agent_run_id: Mapped[str | None] = mapped_column(
        UUID_STR, ForeignKey("agent_runs.agent_run_id"), nullable=True
    )
    relationship_metadata: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, nullable=False, default=dict
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Resolution is a relational column, not a JSONB key: readiness gates on
    # unresolved contradictions, and anything that gates must be queryable
    # without parsing an opaque value (ADR-0012).
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolution_note: Mapped[str | None] = mapped_column(Text, nullable=True)


class ProvenanceLinkRow(Base):
    """Relational link from knowledge to the run or message it came from.

    Keyed by ``(knowledge_item_id, knowledge_version_number)`` rather than a
    foreign key onto ``knowledge_versions.id``, so revision 0001 stays unchanged.
    """

    __tablename__ = "knowledge_provenance_links"
    __table_args__ = (
        Index("ix_provenance_links_item_type", "knowledge_item_id", "link_type"),
        Index("ix_provenance_links_agent_run", "agent_run_id"),
    )

    provenance_link_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    knowledge_item_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("knowledge_items.id"), nullable=False
    )
    knowledge_version_number: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    agent_run_id: Mapped[str | None] = mapped_column(
        UUID_STR, ForeignKey("agent_runs.agent_run_id"), nullable=True
    )
    message_id: Mapped[str | None] = mapped_column(
        UUID_STR, ForeignKey("messages.message_id"), nullable=True
    )
    link_type: Mapped[str] = mapped_column(String(40), nullable=False)
    source_type: Mapped[str | None] = mapped_column(String(40), nullable=True)
    source_reference: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class KnowledgeChunkRow(Base):
    """An embeddable span of a knowledge item.

    ``knowledge_id`` is ``String(64)`` because revision 0001 created
    ``knowledge_items.id`` as ``String(64)``, not a UUID column. Two identifier
    conventions in one table is the accepted cost of leaving 0001 untouched
    (ADR-0008).
    """

    __tablename__ = "knowledge_chunks"
    __table_args__ = (
        UniqueConstraint("knowledge_id", "chunk_index", "embedding_version"),
        Index("ix_knowledge_chunks_project_state", "project_id", "embedding_state"),
        Index("ix_knowledge_chunks_knowledge", "knowledge_id"),
    )

    chunk_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    knowledge_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("knowledge_items.id"), nullable=False
    )
    knowledge_kind: Mapped[str] = mapped_column(String(40), nullable=False)
    chunk_index: Mapped[int] = mapped_column(BigInteger, nullable=False)
    chunk_text: Mapped[str] = mapped_column(Text, nullable=False)

    embedding: Mapped[Any | None] = mapped_column(Vector(1024), nullable=True)
    embedding_state: Mapped[str] = mapped_column(String(20), nullable=False)
    embedding_model: Mapped[str | None] = mapped_column(String(120), nullable=True)
    embedding_dimensions: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    embedding_version: Mapped[int] = mapped_column(BigInteger, nullable=False)

    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    embedded_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ReadinessTemplateRow(Base):
    """A versioned readiness template.

    The area definitions live in ``JSONB`` because their shape is open-ended
    configuration. Nothing gates on them directly — gating reads the snapshot,
    whose every decisive value is a relational column.
    """

    __tablename__ = "readiness_templates"

    template_key: Mapped[str] = mapped_column(String(80), primary_key=True)
    version: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    definition: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class KnowledgeAreaLinkRow(Base):
    """A knowledge item's assignment to a readiness area.

    Endpoints are ``String(64)`` because revision 0001 created
    ``knowledge_items.id`` as ``String(64)``, not a UUID column.
    """

    __tablename__ = "knowledge_area_links"
    __table_args__ = (
        UniqueConstraint("knowledge_item_id", "area_key"),
        Index("ix_knowledge_area_links_project_area", "project_id", "area_key"),
    )

    area_link_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    knowledge_item_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("knowledge_items.id"), nullable=False
    )
    area_key: Mapped[str] = mapped_column(String(80), nullable=False)
    assigned_by_agent_run_id: Mapped[str | None] = mapped_column(
        UUID_STR, ForeignKey("agent_runs.agent_run_id"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class DiscoveryBlockerRow(Base):
    """Something owned that must be closed before a blueprint is credible."""

    __tablename__ = "discovery_blockers"
    __table_args__ = (Index("ix_discovery_blockers_project_status", "project_id", "status"),)

    blocker_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    area_key: Mapped[str | None] = mapped_column(String(80), nullable=True)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False)
    owner: Mapped[str | None] = mapped_column(String(120), nullable=True)
    resolution_note: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class ReadinessSnapshotRow(Base):
    """One append-only readiness calculation.

    Per-area detail is ``JSONB``; every value used for gating — score, status,
    both eligibility flags, and the blocker and contradiction counts — is a
    relational column, so eligibility is queryable without parsing JSON.
    """

    __tablename__ = "readiness_snapshots"
    __table_args__ = (
        Index("ix_readiness_snapshots_project_calculated", "project_id", "calculated_at"),
    )

    snapshot_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        UUID_STR, ForeignKey("projects.project_id"), nullable=False
    )
    template_key: Mapped[str] = mapped_column(String(80), nullable=False)
    template_version: Mapped[int] = mapped_column(BigInteger, nullable=False)
    calculation_version: Mapped[int] = mapped_column(BigInteger, nullable=False)
    knowledge_revision: Mapped[int] = mapped_column(BigInteger, nullable=False)
    score: Mapped[float] = mapped_column(Float, nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    draft_eligible: Mapped[bool] = mapped_column(Boolean, nullable=False)
    implementation_eligible: Mapped[bool] = mapped_column(Boolean, nullable=False)
    mandatory_area_count: Mapped[int] = mapped_column(BigInteger, nullable=False)
    mandatory_area_sufficient_count: Mapped[int] = mapped_column(BigInteger, nullable=False)
    open_blocker_count: Mapped[int] = mapped_column(BigInteger, nullable=False)
    critical_blocker_count: Mapped[int] = mapped_column(BigInteger, nullable=False)
    unresolved_contradiction_count: Mapped[int] = mapped_column(BigInteger, nullable=False)
    area_results: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    calculated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class KnowledgeReviewEventRow(Base):
    """Append-only record of a human decision about a knowledge item.

    ``knowledge_item_id`` is ``String(64)`` to match ``knowledge_items.id``,
    which revision 0001 created as a string rather than a UUID column.
    """

    __tablename__ = "knowledge_review_events"
    __table_args__ = (
        # Idempotency is enforced here rather than by a read-then-insert: a
        # lookup before an insert races, and a replayed confirmation must not
        # produce a second decision even if two clients retry at once.
        UniqueConstraint(
            "knowledge_item_id",
            "idempotency_key",
            name="uq_review_events_item_idempotency",
        ),
        Index("ix_review_events_item_created", "knowledge_item_id", "created_at"),
        Index("ix_review_events_project_created", "project_id", "created_at"),
    )

    review_event_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False)
    knowledge_item_id: Mapped[str] = mapped_column(
        ForeignKey("knowledge_items.id", ondelete="CASCADE"), nullable=False
    )
    version_number: Mapped[int] = mapped_column(BigInteger, nullable=False)
    from_version_number: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    action: Mapped[str] = mapped_column(String(40), nullable=False)
    from_lifecycle: Mapped[str] = mapped_column(String(32), nullable=False)
    to_lifecycle: Mapped[str] = mapped_column(String(32), nullable=False)
    actor_type: Mapped[str] = mapped_column(String(32), nullable=False)
    actor_id: Mapped[str | None] = mapped_column(String(120), nullable=True)
    reason_code: Mapped[str | None] = mapped_column(String(40), nullable=True)
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    idempotency_key: Mapped[str | None] = mapped_column(String(200), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ObservationClassificationRow(Base):
    """One classified span of one submitted observation (T24).

    Derived beside the observation, never over it. The observation stays in
    ``messages`` exactly as submitted; every row here points back at it with a
    real span, so a reviewer can see which words produced which candidate.

    Deliberately not ``knowledge_items``. That table feeds readiness, and
    routing a classified fragment into it would inflate coverage with text
    nobody proposed as a requirement.
    """

    __tablename__ = "observation_classifications"
    __table_args__ = (
        # Idempotency by observation, classifier, version, and span — enforced
        # here rather than by a read-then-insert, which races. Re-running the
        # same classifier version over the same observation must produce no
        # second row even if two workers retry at once.
        UniqueConstraint(
            "message_id",
            "classifier_name",
            "classifier_version",
            "span_start",
            "span_end",
            name="uq_observation_classifications_span",
        ),
        Index("ix_observation_classifications_message", "message_id", "span_start"),
        Index("ix_observation_classifications_project_tier", "project_id", "retention_tier"),
        CheckConstraint("span_end > span_start", name="ck_observation_classifications_span"),
        CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name="ck_observation_classifications_confidence",
        ),
    )

    classification_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False)
    message_id: Mapped[str] = mapped_column(
        ForeignKey("messages.message_id", ondelete="CASCADE"), nullable=False
    )
    classifier_name: Mapped[str] = mapped_column(String(120), nullable=False)
    classifier_version: Mapped[str] = mapped_column(String(40), nullable=False)
    semantic: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    classification: Mapped[str] = mapped_column(String(40), nullable=False)
    retention_tier: Mapped[str] = mapped_column(String(20), nullable=False)
    route: Mapped[str] = mapped_column(String(40), nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    review_required: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    span_start: Mapped[int] = mapped_column(BigInteger, nullable=False)
    span_end: Mapped[int] = mapped_column(BigInteger, nullable=False)
    normalized_text: Mapped[str] = mapped_column(Text, nullable=False)
    extracted_fields: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    # A classifier upgrade produces a new result set and marks the prior one
    # superseded. Past classifications are never mutated: a reviewer's decision
    # was made against what they saw.
    #
    # The *version* that retired this row, not a row id (revision 0012). One old
    # classification is not replaced by one new one — a whole result set is
    # retired when a classifier version changes, and "which version retired
    # this" is the question a history view actually asks.
    superseded_by_version: Mapped[str | None] = mapped_column(String(40), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class OperationalUpdateRow(Base):
    """Where the work stands, as reported (T24.3).

    Separate from knowledge because it answers a different question and decays
    differently. A requirement is true until superseded; a milestone status is
    true until the next one.

    ``authority`` is the field that keeps a sentence from completing a
    milestone. A reported completion is a *proposed transition* carrying what
    was claimed, what is current, and who claimed it.
    """

    __tablename__ = "operational_updates"
    __table_args__ = (
        UniqueConstraint(
            "project_id",
            "idempotency_key",
            name="uq_operational_updates_project_idempotency",
        ),
        Index("ix_operational_updates_project_state", "project_id", "state"),
        Index("ix_operational_updates_subject", "project_id", "subject"),
    )

    operational_update_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False)
    message_id: Mapped[str] = mapped_column(
        ForeignKey("messages.message_id", ondelete="CASCADE"), nullable=False
    )
    classification_id: Mapped[str | None] = mapped_column(UUID_STR, nullable=True)
    kind: Mapped[str] = mapped_column(String(40), nullable=False)
    subject: Mapped[str | None] = mapped_column(String(200), nullable=True)
    reported_status: Mapped[str | None] = mapped_column(String(40), nullable=True)
    current_status: Mapped[str | None] = mapped_column(String(40), nullable=True)
    transition_type: Mapped[str | None] = mapped_column(String(40), nullable=True)
    authority: Mapped[str] = mapped_column(String(40), nullable=False)
    state: Mapped[str] = mapped_column(String(20), nullable=False)
    verification: Mapped[str | None] = mapped_column(String(20), nullable=True)
    effective_date: Mapped[str | None] = mapped_column(String(40), nullable=True)
    date_role: Mapped[str | None] = mapped_column(String(20), nullable=True)
    detail: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    idempotency_key: Mapped[str | None] = mapped_column(String(200), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ModuleRow(Base):
    """One part of the system being defined (N17)."""

    __tablename__ = "modules"
    __table_args__ = (
        # A key is how a person names a module in conversation and how Studio
        # routes to one. Unique per project so `auth` means one thing here and
        # something else in another project, without either having to know.
        UniqueConstraint("project_id", "key", name="uq_modules_project_key"),
        Index("ix_modules_project", "project_id"),
    )

    module_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False)
    key: Mapped[str] = mapped_column(String(120), nullable=False)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False, default="")
    status: Mapped[str] = mapped_column(String(20), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ModuleRelationshipRow(Base):
    """A directed structural edge (N17, ADR-0025).

    Separate from ``knowledge_relationships``, which holds epistemic edges. The
    two vocabularies answer different questions and one table would make every
    read filter for the half it did not want.
    """

    __tablename__ = "module_relationships"
    __table_args__ = (
        # The same edge twice is one edge. Enforced here rather than by a
        # lookup, because a lookup before an insert races and a duplicated
        # `owns` would defeat the exclusivity rule it exists to support.
        UniqueConstraint(
            "source_module_id",
            "relation",
            "target_module_id",
            "target_knowledge_id",
            name="uq_module_relationships_edge",
        ),
        Index("ix_module_relationships_project", "project_id", "relation"),
        Index("ix_module_relationships_source", "source_module_id"),
        Index("ix_module_relationships_target", "target_module_id"),
        CheckConstraint(
            "(target_module_id IS NULL) <> (target_knowledge_id IS NULL)",
            name="ck_module_relationships_one_target",
        ),
        CheckConstraint(
            "target_module_id IS NULL OR target_module_id <> source_module_id",
            name="ck_module_relationships_no_self_edge",
        ),
    )

    module_relationship_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False)
    source_module_id: Mapped[str] = mapped_column(
        ForeignKey("modules.module_id", ondelete="CASCADE"), nullable=False
    )
    relation: Mapped[str] = mapped_column(String(40), nullable=False)
    target_module_id: Mapped[str | None] = mapped_column(
        ForeignKey("modules.module_id", ondelete="CASCADE"), nullable=True
    )
    target_knowledge_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class DeliverableRow(Base):
    """A durable record of an assembled product output (N20).

    Holds identity, ownership, the manifest, hashes, lifecycle, and provenance.
    **Never the artifact bytes.** Rendering and storing content is N21 and
    belongs to whoever owns the destination; a relational row competing with a
    file store for that job would be the worst of both.
    """

    __tablename__ = "deliverables"
    __table_args__ = (
        # Identity is content, not call. Recording the same output twice is one
        # deliverable recorded twice, and the unique index — not a lookup — is
        # what makes that true under two concurrent recordings.
        UniqueConstraint("identity_hash", name="uq_deliverables_identity"),
        Index("ix_deliverables_project_state", "project_id", "state"),
        Index("ix_deliverables_project_recorded", "project_id", "recorded_at"),
        CheckConstraint("knowledge_revision >= 0", name="ck_deliverables_revision"),
        # No `publication_eligible` column: eligibility is derived from the
        # render inputs and the statement pins, and a stored copy drifted from
        # the derived one within a day of shipping (revision 0018).
    )

    deliverable_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False)
    identity_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    purpose: Mapped[str] = mapped_column(String(40), nullable=False)
    scope: Mapped[str] = mapped_column(String(20), nullable=False)
    module_key: Mapped[str | None] = mapped_column(String(120), nullable=True)
    knowledge_revision: Mapped[int] = mapped_column(BigInteger, nullable=False)
    content_hash: Mapped[str] = mapped_column(String(120), nullable=False)
    generator_version: Mapped[str] = mapped_column(String(40), nullable=False, default="")
    state: Mapped[str] = mapped_column(String(20), nullable=False)
    # Metadata only: paths, titles, counts, and per-artifact hashes. The hash is
    # what lets a later renderer prove what it wrote matches what was recorded,
    # without this table ever having held the content.
    artifacts: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, nullable=False, default=list)
    manifest: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    source_knowledge: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    recorded_by: Mapped[str | None] = mapped_column(String(120), nullable=True)
    recorded_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    superseded_by: Mapped[str | None] = mapped_column(UUID_STR, nullable=True)
    # N20.1. Nullable because rows recorded before this existed cannot have it
    # and must not be given it: a fabricated pin would make an unprovable claim
    # look proven.
    # N38. Nullable because a deliverable recorded before qualification existed
    # has none, and inventing one would describe a package nobody described.
    qualification: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    statement_pins: Mapped[list[dict[str, Any]] | None] = mapped_column(JSONB, nullable=True)
    render_inputs: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    # N20.2. Nullable and never backfilled: reconstructing it from today's
    # assumption states would file what the package would mean now under what
    # it meant then, which is the one thing a historical record must not do.
    provisional_context: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)


class AssumptionRow(Base):
    """One interpretation used in place of missing information (N35).

    Deliberately not a `knowledge_item`. That table feeds readiness and is the
    thing a person confirms; an assumption is what KAE proceeded on *because*
    nobody had confirmed anything, and putting the two in one table would make
    the promotion this model forbids a single UPDATE away.
    """

    __tablename__ = "assumptions"
    __table_args__ = (
        Index("ix_assumptions_project_state", "project_id", "state"),
        Index("ix_assumptions_project_subject", "project_id", "subject"),
        CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_assumptions_confidence"),
    )

    assumption_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False)
    subject: Mapped[str] = mapped_column(String(200), nullable=False)
    assumed_value: Mapped[str] = mapped_column(Text, nullable=False)
    reason: Mapped[str] = mapped_column(Text, nullable=False)
    origin: Mapped[str] = mapped_column(String(40), nullable=False)
    consequence: Mapped[str] = mapped_column(String(20), nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    state: Mapped[str] = mapped_column(String(20), nullable=False)
    reversible: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    scope: Mapped[str] = mapped_column(String(40), nullable=False, default="project")
    revisit: Mapped[str] = mapped_column(String(40), nullable=False)
    evidence: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    accepted_by: Mapped[str | None] = mapped_column(String(120), nullable=True)
    delegated: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    supersedes: Mapped[str | None] = mapped_column(UUID_STR, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class SetupQuestionRow(Base):
    """One question about how a project is configured (N25).

    **Deliberately not a `message`.** A clarification is derived from a finding
    and answerable only through it; a setup question has no finding, targets a
    configuration field, and records whether its answer becomes the project
    default. Forcing them together would need a discriminator plus four columns
    meaning nothing for half the rows.
    """

    __tablename__ = "setup_questions"
    __table_args__ = (
        # One question per field per project. Asking someone the same thing
        # twice is what the clarification queue already learned to avoid.
        UniqueConstraint("project_id", "field_name", name="uq_setup_questions_field"),
        Index("ix_setup_questions_project", "project_id", "disposition"),
    )

    setup_question_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False)
    purpose: Mapped[str] = mapped_column(String(40), nullable=False)
    question: Mapped[str] = mapped_column(Text, nullable=False)
    field_name: Mapped[str] = mapped_column(String(120), nullable=False)
    blocking: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    suggested_answer: Mapped[str | None] = mapped_column(Text, nullable=True)
    suggestion_evidence: Mapped[str | None] = mapped_column(Text, nullable=True)
    policy: Mapped[str] = mapped_column(String(40), nullable=False)
    disposition: Mapped[str] = mapped_column(String(40), nullable=False)
    answer: Mapped[str | None] = mapped_column(Text, nullable=True)
    answered_by: Mapped[str | None] = mapped_column(String(120), nullable=True)
    becomes_default: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    revisitable: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    asked_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    answered_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class ProjectConfigurationRow(Base):
    """One configured field, with how it came to have a value (N26).

    One row per field rather than one wide row per project: a field carries a
    state, evidence, a derivation, and who confirmed it — a record, not a value.
    Adding a field is data rather than a migration.

    **No credential column exists**, and the domain refuses a field name that
    looks like one. A column that existed would be serialised by some response
    eventually.
    """

    __tablename__ = "project_configuration"

    project_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    field_name: Mapped[str] = mapped_column(String(120), primary_key=True)
    value: Mapped[str | None] = mapped_column(Text, nullable=True)
    state: Mapped[str] = mapped_column(String(40), nullable=False)
    evidence: Mapped[str] = mapped_column(Text, nullable=False, default="")
    derived_from_knowledge_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    confirmed_by: Mapped[str | None] = mapped_column(String(120), nullable=True)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ProviderConnectionRow(Base):
    """Permission to reach one provider, without the means of doing so (N28).

    `credential_reference` names *where* a credential is — an environment
    variable, a secret-manager path. There is no column for the credential
    itself, on purpose: a field that exists gets serialised, and the response
    that leaks it is written by someone who did not know it was there.
    """

    __tablename__ = "provider_connections"
    __table_args__ = (Index("ix_provider_connections_project", "project_id", "provider"),)

    connection_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False)
    provider: Mapped[str] = mapped_column(String(40), nullable=False)
    state: Mapped[str] = mapped_column(String(40), nullable=False)
    credential_reference: Mapped[str | None] = mapped_column(String(400), nullable=True)
    authorized_by: Mapped[str | None] = mapped_column(String(120), nullable=True)
    last_verified_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    detail: Mapped[str] = mapped_column(Text, nullable=False, default="")


class PublicationTargetRow(Base):
    """A registered destination, described without the means to reach it (N27).

    Separate from the connection because a target is a **product decision** and
    a connection is a runtime permission. A token expiring must not erase a
    decision about where to publish, and re-asking someone to choose a
    destination they already chose is how a system teaches people to ignore it.
    """

    __tablename__ = "publication_targets"
    __table_args__ = (
        UniqueConstraint("project_id", "name", name="uq_publication_targets_name"),
        Index("ix_publication_targets_project", "project_id", "purpose"),
        # At most one default per purpose, by index rather than read-then-write:
        # two concurrent "make this the default" calls would both find none.
        Index(
            "uq_publication_targets_default",
            "project_id",
            "purpose",
            unique=True,
            postgresql_where=text("is_default"),
        ),
    )

    target_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False)
    provider: Mapped[str] = mapped_column(String(40), nullable=False)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    purpose: Mapped[str] = mapped_column(String(40), nullable=False)
    is_default: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    configuration: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    connection_id: Mapped[str | None] = mapped_column(UUID_STR, nullable=True)
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class PublicationAttemptRow(Base):
    """One attempt to write one deliverable to one target (N29).

    Append-oriented: a retry is a new row, never an update. "It failed twice and
    then worked" is exactly the history an operator needs when it fails a third
    time, and an overwriting design destroys it.

    Separate from `deliverables` because an attempt is an event and a
    deliverable is a record of an output that exists. A failed attempt must
    never modify an immutable record, and must never make a provider outage
    look like a property of the document.
    """

    __tablename__ = "publication_attempts"
    __table_args__ = (
        Index("ix_publication_attempts_deliverable", "deliverable_id", "requested_at"),
        Index("ix_publication_attempts_project", "project_id", "state"),
    )

    attempt_id: Mapped[str] = mapped_column(UUID_STR, primary_key=True)
    project_id: Mapped[str] = mapped_column(String(64), nullable=False)
    deliverable_id: Mapped[str] = mapped_column(String(64), nullable=False)
    target_id: Mapped[str] = mapped_column(String(64), nullable=False)
    provider: Mapped[str] = mapped_column(String(40), nullable=False)
    state: Mapped[str] = mapped_column(String(40), nullable=False)
    package_hash: Mapped[str | None] = mapped_column(String(120), nullable=True)
    package_size: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    # What was written, never how to reach it with a signature. There is no
    # column for a download URL, on purpose.
    external_reference: Mapped[str | None] = mapped_column(Text, nullable=True)
    verification_passed: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    error_category: Mapped[str] = mapped_column(String(40), nullable=False, default="none")
    error_detail: Mapped[str] = mapped_column(Text, nullable=False, default="")
    requested_by: Mapped[str | None] = mapped_column(String(120), nullable=True)
    requested_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
