"""The published capability matrix matches the registry it claims to describe.

`docs/reference/capability-matrix.md` is generated from
`src/kae_memory/capabilities.py`. Generating it was the easy half; this is the
half that makes it worth doing.

Without this, the page is a copy — correct on the day it was written and quietly
wrong afterwards, because nothing tests prose. A capability added to the
registry would be enforced on both adapters by `test_adapter_parity.py` and
absent from the documentation, and the documentation is what a reader believes.

The failure message names the command that fixes it, because a test that says
only "does not match" makes the reader go and find out how.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
GENERATOR = REPO / "scripts" / "development" / "generate-capability-matrix.py"
PAGE = REPO / "docs" / "reference" / "capability-matrix.md"


class TestTheGeneratedPageIsCurrent:
    def test_it_matches_the_registry(self) -> None:
        result = subprocess.run(
            [sys.executable, str(GENERATOR), "--check"],
            capture_output=True,
            text=True,
            cwd=REPO,
        )

        assert result.returncode == 0, (
            f"{result.stdout}{result.stderr}\n"
            "The capability registry and the published matrix disagree."
        )

    def test_the_page_says_it_is_generated(self) -> None:
        """So nobody edits it by hand and loses the edit on the next run."""

        assert PAGE.read_text().startswith("<!-- Generated by")


class TestTheInterfaceReferenceIsCurrent:
    """The MCP tools and HTTP API pages against the sources they are drawn from.

    Same argument as the matrix, twice over. The capability registry and the
    recorded OpenAPI contract are each already guarded; these pages are a third
    rendering, and a rendering nothing checks is a rendering that goes stale
    without anyone noticing.
    """

    GENERATOR = REPO / "scripts" / "development" / "generate-interface-reference.py"

    def test_it_matches_the_registry_and_contract(self) -> None:
        result = subprocess.run(
            [sys.executable, str(self.GENERATOR), "--check"],
            capture_output=True,
            text=True,
            cwd=REPO,
        )

        assert result.returncode == 0, (
            f"{result.stdout}{result.stderr}\n"
            "The interface reference and its sources disagree."
        )

    def test_every_declared_tool_is_documented(self) -> None:
        """A tool that exists and is undocumented is worse than one that does
        not exist: a client discovers it, and nothing says what it is for."""

        from kae_memory.capabilities import declared_mcp_tools

        page = (REPO / "docs" / "reference" / "mcp-tools.md").read_text()
        missing = sorted(t for t in declared_mcp_tools() if f"`{t}`" not in page)

        assert not missing, f"declared but undocumented: {missing}"
