"""The published capability matrix matches the registry it claims to describe.

`docs/reference/capability-matrix.md` is generated from
`src/kae_memory/capabilities.py`. Generating it was the easy half; this is the
half that makes it worth doing.

Without this, the page is a copy — correct on the day it was written and quietly
wrong afterwards, because nothing tests prose. A capability added to the
registry would be enforced on both adapters by `test_adapter_parity.py` and
absent from the documentation, and the documentation is what a reader believes.

The failure message names the command that fixes it, because a test that says
only "does not match" makes the reader go and find out how.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
GENERATOR = REPO / "scripts" / "development" / "generate-capability-matrix.py"
PAGE = REPO / "docs" / "reference" / "capability-matrix.md"


class TestTheGeneratedPageIsCurrent:
    def test_it_matches_the_registry(self) -> None:
        result = subprocess.run(
            [sys.executable, str(GENERATOR), "--check"],
            capture_output=True,
            text=True,
            cwd=REPO,
        )

        assert result.returncode == 0, (
            f"{result.stdout}{result.stderr}\n"
            "The capability registry and the published matrix disagree."
        )

    def test_the_page_says_it_is_generated(self) -> None:
        """So nobody edits it by hand and loses the edit on the next run."""

        assert PAGE.read_text().startswith("<!-- Generated by")
