/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description FR-017. Unversioned on purpose: an operational probe should not move
         *     when the business contract does.
         *
         *     Reports ``degraded`` rather than ``ok`` when the database is unreachable,
         *     and never returns a connection string — the URL contains the password.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/{item_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Knowledge
         * @description Confirm a candidate.
         *
         *     Confirmation is a human act. No agent performs it, which is why this is an
         *     endpoint and not a step inside a run.
         */
        post: operations["confirm_knowledge_v1_knowledge__item_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/{item_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trace Knowledge
         * @description Return a knowledge item's chain of custody.
         *
         *     Project, the sessions and messages it came from, the run that produced it,
         *     the runs that consumed it, and every version with its provenance — the answer
         *     to "why does the blueprint say this?"
         */
        get: operations["trace_knowledge_v1_knowledge__item_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description List every project, newest first.
         */
        get: operations["list_projects_v1_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Create a durable project.
         */
        post: operations["create_project_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Return one project.
         */
        get: operations["get_project_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/blockers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Blockers
         * @description List a project's blockers.
         */
        get: operations["list_blockers_v1_projects__project_id__blockers_get"];
        put?: never;
        /**
         * Raise Blocker
         * @description Record something that must be closed before a blueprint is credible.
         */
        post: operations["raise_blocker_v1_projects__project_id__blockers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/blockers/{blocker_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Blocker
         * @description Close a blocker.
         */
        post: operations["resolve_blocker_v1_projects__project_id__blockers__blocker_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/blueprint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Blueprint
         * @description Render confirmed knowledge as a blueprint.
         *
         *     Returned even below the draft threshold, marked incomplete. Refusing would
         *     tell a user nothing about *what is missing*, and for an early project the
         *     missing-area list is the most useful thing the blueprint can say.
         *
         *     Every statement is a confirmed knowledge item's own text. No model writes
         *     blueprint prose (ADR-0016), because generated connective text would be
         *     unattributable — the failure FR-008's labelling exists to prevent.
         */
        get: operations["get_blueprint_v1_projects__project_id__blueprint_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/blueprint.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Blueprint
         * @description Export the same blueprint as Markdown (FR-008).
         *
         *     A rendering of the same structure the JSON exposes, so the two cannot
         *     disagree. Every statement keeps its label and knowledge identifier, so an
         *     exported document is as traceable as the API response.
         */
        get: operations["export_blueprint_v1_projects__project_id__blueprint_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/contradictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Contradiction
         * @description Record that two knowledge items contradict each other.
         *
         *     An unresolved contradiction touching a mandatory area blocks readiness, which
         *     is what makes this more than an annotation.
         */
        post: operations["record_contradiction_v1_projects__project_id__contradictions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/contradictions/{relationship_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Contradiction
         * @description Resolve a contradiction.
         *
         *     ``resolved: false`` means it was already settled. That is not an error — a
         *     retried resolution has to be safe — and the edge is never deleted, because a
         *     contradiction that was raised and closed is part of the audit trail.
         */
        post: operations["resolve_contradiction_v1_projects__project_id__contradictions__relationship_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Knowledge
         * @description List a project's knowledge.
         *
         *     Unfiltered by default. The workspace needs to show proposed candidates beside
         *     confirmed knowledge, because the difference between them is the thing a user
         *     acts on.
         */
        get: operations["list_knowledge_v1_projects__project_id__knowledge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Readiness
         * @description Return the latest snapshot, calculating one if none exists.
         *
         *     Calculating on first read rather than returning 404 means the workspace shows
         *     a real zero for an untouched project instead of an error it would have to
         *     explain.
         */
        get: operations["get_readiness_v1_projects__project_id__readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/readiness/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Area
         * @description Link a knowledge item to a discovery area.
         *
         *     An authoritative change: it alters which areas an item can cover, so the
         *     project's knowledge revision advances and earlier snapshots go stale.
         */
        post: operations["assign_area_v1_projects__project_id__readiness_areas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/readiness/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Readiness
         * @description Recalculate and append a snapshot.
         *
         *     Appends rather than replaces. Readiness history is how the product shows
         *     readiness *moving* as knowledge is confirmed.
         */
        post: operations["calculate_readiness_v1_projects__project_id__readiness_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/readiness/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness History
         * @description Return snapshots oldest first.
         */
        get: operations["readiness_history_v1_projects__project_id__readiness_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Findings
         * @description Return quality findings, most severe first (FR-015).
         *
         *     Derived from operational data on every request rather than stored, so the
         *     findings can never disagree with the state they describe. Acting on one means
         *     changing that state — confirm the knowledge, assign the area, resolve the
         *     contradiction — and the finding disappears.
         */
        get: operations["review_findings_v1_projects__project_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List a project's execution history, most recent first.
         */
        get: operations["list_runs_v1_projects__project_id__runs_get"];
        put?: never;
        /**
         * Enqueue Run
         * @description Enqueue agent work and return immediately.
         *
         *     **202, never 200.** The run is durable when this returns, but it has not
         *     started: a worker claims it. The browser does not own the run (ADR-0009), so
         *     closing the tab cannot lose it.
         *
         *     Idempotent on ``idempotency_key`` — a retried request converges on the
         *     original run rather than creating a second.
         */
        post: operations["enqueue_run_v1_projects__project_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List a project's sessions.
         */
        get: operations["list_sessions_v1_projects__project_id__sessions_get"];
        put?: never;
        /**
         * Open Session
         * @description Open a working session.
         */
        post: operations["open_session_v1_projects__project_id__sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Return one run. This is what a client polls while work proceeds.
         */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description Stream run progress as Server-Sent Events.
         *
         *     A convenience over ``GET /v1/runs/{id}``, never a replacement for it.
         *     Correctness must not depend on an uninterrupted browser connection
         *     (ADR-0009), so a client that misses the stream entirely can still read the
         *     same state with an ordinary request.
         *
         *     Emits the current state immediately, then on every change to status,
         *     attempt, checkpoint, or error. Closes when the run reaches a terminal
         *     status.
         */
        get: operations["stream_run_events_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Knowledge Produced By
         * @description Return the knowledge a run produced.
         *
         *     One run, one result: replaying a completed run returns its original output
         *     rather than producing a second set.
         */
        get: operations["knowledge_produced_by_v1_runs__run_id__knowledge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Session
         * @description Close a session.
         */
        post: operations["close_session_v1_sessions__session_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description List a session's messages in submission order.
         */
        get: operations["list_messages_v1_sessions__session_id__messages_get"];
        put?: never;
        /**
         * Record Message
         * @description Record a message verbatim as source evidence.
         *
         *     The stored text is never rewritten by extraction, so the original wording
         *     stays available as the source of anything derived from it.
         */
        post: operations["record_message_v1_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AreaResultResponse */
        AreaResultResponse: {
            /** Confirmed Count */
            confirmed_count: number;
            /** Contradicted */
            contradicted: boolean;
            /** Key */
            key: string;
            /** Mandatory */
            mandatory: boolean;
            /** Minimum Confirmed */
            minimum_confirmed: number;
            /** Name */
            name: string;
            /** Proposed Count */
            proposed_count: number;
            /** State */
            state: string;
            /** Weight */
            weight: number;
        };
        /** AssignAreaRequest */
        AssignAreaRequest: {
            /** Area Key */
            area_key: string;
            /** Knowledge Item Id */
            knowledge_item_id: string;
        };
        /** BlockerResponse */
        BlockerResponse: {
            /** Area Key */
            area_key: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Owner */
            owner: string | null;
            /** Project Id */
            project_id: string;
            /** Resolution Note */
            resolution_note: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
        };
        /**
         * BlueprintResponse
         * @description A blueprint, with its own limits attached rather than implied.
         */
        BlueprintResponse: {
            /** Complete */
            complete: boolean;
            /** Draft Eligible */
            draft_eligible: boolean;
            /** Implementation Eligible */
            implementation_eligible: boolean;
            /** Missing Mandatory Areas */
            missing_mandatory_areas: string[];
            /** Open Questions */
            open_questions: string[];
            /** Project Id */
            project_id: string;
            /** Project Name */
            project_name: string;
            /** Readiness Percentage */
            readiness_percentage: number;
            /** Sections */
            sections: components["schemas"]["SectionResponse"][];
            /** Statement Count */
            statement_count: number;
            /** Unassigned Confirmed Count */
            unassigned_confirmed_count: number;
        };
        /** CalculateReadinessRequest */
        CalculateReadinessRequest: {
            /** Not Applicable Areas */
            not_applicable_areas?: string[];
        };
        /** ContradictionResponse */
        ContradictionResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Source Knowledge Item Id */
            source_knowledge_item_id: string;
            /** Target Knowledge Item Id */
            target_knowledge_item_id: string;
        };
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /** Description */
            description?: string | null;
            /** Key */
            key?: string | null;
            /** Name */
            name: string;
        };
        /**
         * EnqueueRunRequest
         * @description ``idempotency_key`` is required, not optional.
         *
         *     ``MemoryService`` deduplicates on it, so a client that retries a request it
         *     never saw the answer to converges on one run instead of two. Making it
         *     optional would leave the one durable replay protection this API has to a
         *     caller's discretion.
         */
        EnqueueRunRequest: {
            /** Idempotency Key */
            idempotency_key: string;
            /** Input Context */
            input_context?: {
                [key: string]: unknown;
            };
            /** Role */
            role: string;
            /** Session Id */
            session_id?: string | null;
        };
        /**
         * FindingResponse
         * @description One quality finding.
         *
         *     No identifier, deliberately: findings are derived from state, not stored, so
         *     there is nothing stable to address. A finding disappears when the condition
         *     that produced it does (ADR-0015).
         */
        FindingResponse: {
            /** Area Key */
            area_key: string | null;
            /** Kind */
            kind: string;
            /** Knowledge Item Ids */
            knowledge_item_ids: string[];
            /** Recommended Action */
            recommended_action: string;
            /** Severity */
            severity: string;
            /** Summary */
            summary: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description FR-017. Reports without authentication and without leaking credentials.
         */
        HealthResponse: {
            /** Database */
            database: string;
            /** Migration Revision */
            migration_revision: string | null;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * KnowledgeResponse
         * @description Carries every version, because history is the product.
         *
         *     A knowledge item that only exposes its current text would make the audit
         *     trail invisible to the interface that exists to show it.
         */
        KnowledgeResponse: {
            /** Current Content */
            current_content: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Lifecycle */
            lifecycle: string;
            /** Project Id */
            project_id: string;
            /** Versions */
            versions: components["schemas"]["KnowledgeVersionResponse"][];
        };
        /** KnowledgeVersionResponse */
        KnowledgeVersionResponse: {
            /** Content */
            content: string;
            /** Number */
            number: number;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Source */
            source: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Actor Type */
            actor_type: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Message Type */
            message_type: string;
            /** Sequence Number */
            sequence_number: number;
            /** Session Id */
            session_id: string;
        };
        /** OpenSessionRequest */
        OpenSessionRequest: {
            /** Session Type */
            session_type: string;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Key */
            key: string | null;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /** RaiseBlockerRequest */
        RaiseBlockerRequest: {
            /** Area Key */
            area_key?: string | null;
            /** Owner */
            owner?: string | null;
            /**
             * Severity
             * @default critical
             */
            severity: string;
            /** Summary */
            summary: string;
        };
        /**
         * ReadinessResponse
         * @description Everything needed to interrogate the number, never the number alone.
         *
         *     ``is_stale`` is computed against the project's current revision at read time,
         *     which is why it is not a stored status.
         */
        ReadinessResponse: {
            /** Areas */
            areas: components["schemas"]["AreaResultResponse"][];
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
            /** Calculation Version */
            calculation_version: number;
            /** Critical Blocker Count */
            critical_blocker_count: number;
            /** Draft Eligible */
            draft_eligible: boolean;
            /** Id */
            id: string;
            /** Implementation Eligible */
            implementation_eligible: boolean;
            /** Is Stale */
            is_stale: boolean;
            /** Knowledge Revision */
            knowledge_revision: number;
            /** Missing Mandatory Areas */
            missing_mandatory_areas: string[];
            /** Open Blocker Count */
            open_blocker_count: number;
            /** Percentage */
            percentage: number;
            /** Project Id */
            project_id: string;
            /** Score */
            score: number;
            /** Status */
            status: string;
            /** Template Key */
            template_key: string;
            /** Template Version */
            template_version: number;
            /** Unresolved Contradiction Count */
            unresolved_contradiction_count: number;
        };
        /** RecordContradictionRequest */
        RecordContradictionRequest: {
            /** Source Knowledge Item Id */
            source_knowledge_item_id: string;
            /** Target Knowledge Item Id */
            target_knowledge_item_id: string;
        };
        /** RecordMessageRequest */
        RecordMessageRequest: {
            /** Actor Id */
            actor_id?: string | null;
            /**
             * Actor Type
             * @default user
             */
            actor_type: string;
            /** Content */
            content: string;
            /**
             * Message Type
             * @default input
             */
            message_type: string;
        };
        /** ResolveRequest */
        ResolveRequest: {
            /** Note */
            note?: string | null;
        };
        /**
         * ResolvedResponse
         * @description Whether the call changed anything.
         *
         *     ``False`` means it was already resolved, which is not an error — a retried
         *     resolution should be safe.
         */
        ResolvedResponse: {
            /** Resolved */
            resolved: boolean;
        };
        /**
         * ReviewResponse
         * @description What a reviewer needs without inspecting the database (FR-015).
         */
        ReviewResponse: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Findings */
            findings: components["schemas"]["FindingResponse"][];
            /** Project Id */
            project_id: string;
        };
        /** RunResponse */
        RunResponse: {
            /** Attempt Number */
            attempt_number: number;
            /** Continuation State */
            continuation_state: {
                [key: string]: unknown;
            };
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Output Summary */
            output_summary: {
                [key: string]: unknown;
            };
            /** Project Id */
            project_id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** SectionResponse */
        SectionResponse: {
            /** Area Key */
            area_key: string;
            /** Area Name */
            area_name: string;
            /** Statements */
            statements: components["schemas"]["StatementResponse"][];
        };
        /** SessionResponse */
        SessionResponse: {
            /** Ended At */
            ended_at: string | null;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Type */
            type: string;
        };
        /**
         * StatementResponse
         * @description One blueprint statement.
         *
         *     Carries its knowledge item, so tracing it is one hop rather than a parallel
         *     trace API over derived identifiers (ADR-0016). No statement lacks a label or
         *     a trace target — FR-008's acceptance condition, and it holds structurally.
         */
        StatementResponse: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Knowledge Item Id */
            knowledge_item_id: string;
            /** Knowledge Version */
            knowledge_version: number;
            /** Label */
            label: string;
            /** Produced By Run Id */
            produced_by_run_id: string | null;
            /** Source Message Id */
            source_message_id: string | null;
            /** Text */
            text: string;
        };
        /**
         * TraceResponse
         * @description A knowledge item's chain of custody: project, session, message, run, versions.
         */
        TraceResponse: {
            /** Current Content */
            current_content: string;
            /** Kind */
            kind: string;
            /** Knowledge Item Id */
            knowledge_item_id: string;
            /** Lifecycle */
            lifecycle: string;
            /** Produced By Run Id */
            produced_by_run_id: string | null;
            /** Project Id */
            project_id: string;
            /** Session Ids */
            session_ids: string[];
            /** Source Message Ids */
            source_message_ids: string[];
            /** Steps */
            steps: components["schemas"]["TraceStepResponse"][];
            /** Used By Run Ids */
            used_by_run_ids: string[];
        };
        /** TraceStepResponse */
        TraceStepResponse: {
            /** Detail */
            detail: string | null;
            /** Reference */
            reference: string;
            /** Relation */
            relation: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    confirm_knowledge_v1_knowledge__item_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_knowledge_v1_knowledge__item_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    create_project_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_blockers_v1_projects__project_id__blockers_get: {
        parameters: {
            query?: {
                blocker_status?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockerResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    raise_blocker_v1_projects__project_id__blockers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RaiseBlockerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_blocker_v1_projects__project_id__blockers__blocker_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                blocker_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blueprint_v1_projects__project_id__blueprint_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_blueprint_v1_projects__project_id__blueprint_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": unknown;
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_contradiction_v1_projects__project_id__contradictions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordContradictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContradictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_contradiction_v1_projects__project_id__contradictions__relationship_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                relationship_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_v1_projects__project_id__knowledge_get: {
        parameters: {
            query?: {
                lifecycle?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_readiness_v1_projects__project_id__readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_area_v1_projects__project_id__readiness_areas_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignAreaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_readiness_v1_projects__project_id__readiness_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculateReadinessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readiness_history_v1_projects__project_id__readiness_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_findings_v1_projects__project_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_v1_projects__project_id__runs_get: {
        parameters: {
            query?: {
                run_status?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_run_v1_projects__project_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnqueueRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_v1_projects__project_id__sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_session_v1_projects__project_id__sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_v1_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    knowledge_produced_by_v1_runs__run_id__knowledge_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_session_v1_sessions__session_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_v1_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_message_v1_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
