"""Generate the MCP tools and HTTP API reference pages.

Both come from sources that already have a guard: the capability registry in
`src/kae_memory/capabilities.py`, which `tests/api/test_adapter_parity.py`
checks both adapters against, and `specifications/openapi.json`, which
`tests/api/test_recorded_contract.py` compares to the live app.

Writing either by hand would mean maintaining a third copy of something two
tests already keep honest, and prose is the copy nothing checks.

    uv run python scripts/development/generate-interface-reference.py --check
    uv run python scripts/development/generate-interface-reference.py --write
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from kae_memory.capabilities import REGISTRY, Exposure

REPO = Path(__file__).resolve().parents[2]
MCP_PAGE = REPO / "docs" / "reference" / "mcp-tools.md"
HTTP_PAGE = REPO / "docs" / "reference" / "http-api.md"
CONTRACT = REPO / "specifications" / "openapi.json"

#: Operations that change durable state. Derived from the operation verb rather
#: than from a flag, because no flag exists — and stated here so a reader can
#: check the classification rather than take it on trust. Cross-checked against
#: the HTTP method: every mutation below is a POST, and every GET is a read.
MUTATING_VERBS = frozenset(
    {
        "submit",
        "confirm",
        "reject",
        "correct",
        "create",
        "record",
        "define",
        "relate",
        "answer",
        "accept",
        "settle",
        "ingest",
    }
)


def _mutates(tool: str) -> bool:
    padded = f"_{tool}_"
    return any(f"_{v}_" in padded or tool.startswith(f"kae_{v}") for v in MUTATING_VERBS)


def render_mcp() -> str:
    by_tool = {t: c for c in REGISTRY for t in c.mcp}
    mutations = sorted(t for t in by_tool if _mutates(t))
    reads = sorted(t for t in by_tool if not _mutates(t))

    out = [
        "<!-- Generated by scripts/development/generate-interface-reference.py.",
        "     Edit src/kae_memory/capabilities.py, not this file. -->",
        "",
        "# MCP tools",
        "",
        f"{len(by_tool)} tools. **{len(mutations)} of them change durable state** — MCP is not a",
        "read-only surface, and never was; ADR-0004's title said *CockroachDB MCP*, and",
        "[ADR-0027](../../specifications/ADR/ADR-0027-application-contracts-are-the-write-path.md)",
        "restates the boundary without the confusion.",
        "",
        "What a tool is *for* is below. Argument and return shapes come from the tool",
        "schemas your MCP client discovers at connection — they are the contract, and",
        "copying them here would create a second one.",
        "",
        "> **Under active development.** These describe the current implementation and",
        "> carry no backward-compatibility guarantee.",
        "",
        "---",
        "",
        f"## Reads ({len(reads)})",
        "",
        "| Tool | What it answers | Capability |",
        "|---|---|---|",
    ]
    for t in reads:
        c = by_tool[t]
        out.append(f"| `{t}` | {c.summary} | `{c.key}` |")

    out += [
        "",
        "---",
        "",
        f"## Mutations ({len(mutations)})",
        "",
        "Each records something durably. **None of them confirms knowledge on its own**",
        "except the explicit review tools — everything submitted arrives as a candidate.",
        "See [the knowledge lifecycle](../concepts/knowledge-lifecycle.md).",
        "",
        "| Tool | What it records | Capability |",
        "|---|---|---|",
    ]
    for t in mutations:
        c = by_tool[t]
        out.append(f"| `{t}` | {c.summary} | `{c.key}` |")

    agent_only = sorted(t for t, c in by_tool.items() if c.exposure is Exposure.AGENT_ONLY)
    out += [
        "",
        "---",
        "",
        "## Reachable over MCP only",
        "",
        "Not gaps. Each is a decision with a reason recorded in the registry, shown in",
        "full in the [capability matrix](capability-matrix.md).",
        "",
    ]
    for t in agent_only:
        out.append(f"- `{t}` — {by_tool[t].summary}")

    out += [
        "",
        "---",
        "",
        "## Related",
        "",
        "- [Capability matrix](capability-matrix.md) — which adapter has what, and why",
        "- [Response policy](response-policy.md) — how much detail comes back",
        "- [Access and mutation policy](access-and-mutation-policy.md) — what a client may do",
        "",
    ]
    return "\n".join(out)


def render_http() -> str:
    # The registry's summaries are written for a reader; FastAPI's are the
    # operation name with spaces in it. Prefer the former where a route is
    # declared, and fall back rather than leaving a cell empty.
    by_route = {r: c.summary for c in REGISTRY for r in c.http}

    def purpose(method: str, path: str, detail: dict) -> str:
        return (
            by_route.get(f"{method} {path}")
            or detail.get("summary")
            or detail.get("operationId", "")
        )

    spec = json.loads(CONTRACT.read_text())
    paths = spec["paths"]
    ops = [(p, m.upper(), v[m]) for p, v in sorted(paths.items()) for m in sorted(v)]
    gets = [o for o in ops if o[1] == "GET"]
    posts = [o for o in ops if o[1] == "POST"]

    out = [
        "<!-- Generated by scripts/development/generate-interface-reference.py.",
        "     Edit the application routes; specifications/openapi.json is recorded from them. -->",
        "",
        "# HTTP API",
        "",
        f"{len(paths)} paths, {len(ops)} operations — {len(gets)} GET, {len(posts)} POST.",
        "",
        "Recorded in [`specifications/openapi.json`](../../specifications/openapi.json),",
        "which `tests/api/test_recorded_contract.py` compares against the running",
        "application. A route that changes without the contract changing fails the suite.",
        "",
        "Request and response schemas are in that document. This page is the map.",
        "",
        "> **Authentication.** Off-loopback the process refuses to start without",
        "> `KAE_API_TOKENS`"
        " ([ADR-0024](../../specifications/ADR/ADR-0024-http-trust-boundary.md)).",
        "> See [configuration](configuration.md) for the format and",
        "> [security boundaries](../architecture/security-boundaries.md) for what that does",
        "> and does not cover.",
        "",
        "> **Under active development.** No backward-compatibility guarantee.",
        "",
        "---",
        "",
        f"## Reads ({len(gets)})",
        "",
        "| Route | Purpose |",
        "|---|---|",
    ]
    for p, _, detail in gets:
        out.append(f"| `GET {p}` | {purpose('GET', p, detail)} |")

    out += [
        "",
        "---",
        "",
        f"## Writes ({len(posts)})",
        "",
        "POST throughout, including some operations that read. Listing clarifications",
        "**materialises** the questions it returns, so it is a POST deliberately — a GET",
        "that mutates is one a browser prefetch performs again",
        "([ADR-0023](../../specifications/ADR/ADR-0023-http-and-mcp-as-peer-adapters.md)).",
        "",
        "| Route | Purpose |",
        "|---|---|",
    ]
    for p, _, detail in posts:
        out.append(f"| `POST {p}` | {purpose('POST', p, detail)} |")

    out += [
        "",
        "---",
        "",
        "## Related",
        "",
        "- [Capability matrix](capability-matrix.md) — HTTP-only capabilities and why",
        "- [Errors](errors.md)",
        "- [Configuration](configuration.md)",
        "",
    ]
    return "\n".join(out)


TARGETS = ((MCP_PAGE, render_mcp), (HTTP_PAGE, render_http))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    if args.check:
        stale = [p for p, r in TARGETS if not p.exists() or p.read_text() != r()]
        if stale:
            for p in stale:
                print(f"{p} is stale", file=sys.stderr)
            print(
                "Regenerate: uv run python scripts/development/"
                "generate-interface-reference.py --write",
                file=sys.stderr,
            )
            return 1
        print("interface reference is current")
        return 0

    if args.write:
        for page, render in TARGETS:
            page.parent.mkdir(parents=True, exist_ok=True)
            page.write_text(render())
            print(f"wrote {page}")
        return 0

    parser.print_help()
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
