"""Generate the capability matrix page from the registry that enforces it.

`docs/reference/capability-matrix.md` is not written by hand. The registry in
`src/kae_memory/capabilities.py` is what `tests/api/test_adapter_parity.py`
checks both adapters against, so it is already the authority — a hand-maintained
copy would be a second answer to a question that has one, and it would drift
quietly because nothing tests prose.

Generating it means drift becomes a failing test rather than a stale page.

    uv run python scripts/development/generate-capability-matrix.py --check
    uv run python scripts/development/generate-capability-matrix.py --write

`--check` exits non-zero when the committed page no longer matches the registry,
which is the form a CI step wants.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from kae_memory.capabilities import REGISTRY, Exposure

PAGE = Path(__file__).resolve().parents[2] / "docs" / "reference" / "capability-matrix.md"

HEADING = {
    Exposure.BOTH: (
        "## On both adapters",
        "Reachable over MCP and HTTP. `tests/api/test_adapter_parity.py` fails if\n"
        "either is missing one of these — absence is a defect, not a decision.",
    ),
    Exposure.PRODUCT_ONLY: (
        "## HTTP only, by decision",
        "The product surface. Present on MCP would be the defect, and each row\n"
        "carries the reason it is not there.",
    ),
    Exposure.AGENT_ONLY: (
        "## MCP only, by decision",
        "The agent surface. Same rule in the other direction.",
    ),
    Exposure.INTERNAL: (
        "## Neither adapter",
        "Operational or administrative, reached another way. **Not part of the\n"
        "supported client surface** and not something to build against.",
    ),
}


def render() -> str:
    counts = {e: sum(1 for c in REGISTRY if c.exposure is e) for e in Exposure}
    out: list[str] = [
        "<!-- Generated by scripts/development/generate-capability-matrix.py.",
        "     Edit src/kae_memory/capabilities.py, not this file. -->",
        "",
        "# Capability matrix",
        "",
        "What each adapter exposes, from the registry that enforces it.",
        "",
        "**The two adapters are peers, not mirrors** (ADR-0023). They share the same",
        "application services, and where they differ, the difference is declared and",
        "carries a reason. Parity means the registry decides what belongs where — not",
        "that every operation appears twice.",
        "",
        f"{len(REGISTRY)} capabilities: "
        f"{counts[Exposure.BOTH]} on both, "
        f"{counts[Exposure.PRODUCT_ONLY]} HTTP only, "
        f"{counts[Exposure.AGENT_ONLY]} MCP only, "
        f"{counts[Exposure.INTERNAL]} on neither.",
        "",
        "This page is generated from `src/kae_memory/capabilities.py`, which",
        "`tests/api/test_adapter_parity.py` checks in both directions: a declared",
        "capability missing from an adapter fails the suite, and so does a tool or",
        "route the registry does not declare.",
        "",
    ]

    for exposure in (
        Exposure.BOTH,
        Exposure.PRODUCT_ONLY,
        Exposure.AGENT_ONLY,
        Exposure.INTERNAL,
    ):
        rows = [c for c in REGISTRY if c.exposure is exposure]
        if not rows:
            continue
        title, blurb = HEADING[exposure]
        out += ["---", "", f"{title} ({len(rows)})", "", blurb, ""]

        has_reason = any(c.reason for c in rows)
        header = "| Capability | What it does | MCP | HTTP |"
        divider = "|---|---|---|---|"
        if has_reason:
            header += " Why only here |"
            divider += "---|"
        out += [header, divider]

        for c in sorted(rows, key=lambda x: x.key):
            mcp = ", ".join(f"`{t}`" for t in c.mcp) or "—"
            http = ", ".join(f"`{r}`" for r in c.http) or "—"
            row = f"| `{c.key}` | {c.summary} | {mcp} | {http} |"
            if has_reason:
                row += f" {c.reason or '—'} |"
            out.append(row)
        out.append("")

    out += [
        "---",
        "",
        "## Reading this",
        "",
        "**A capability is not a route.** Several carry more than one route or tool;",
        "the capability is the unit of function, and the adapter entries are how it is",
        "reached.",
        "",
        "**An empty column is deliberate.** Nothing is absent by accident — the parity",
        "test would fail. Where a capability sits on one adapter only, the reason",
        "column says why the other would be wrong.",
        "",
        "**Internal capabilities are not a client surface.** They appear here so the",
        "registry is complete, not as something to call.",
        "",
        "## Related",
        "",
        "- [MCP tools reference](mcp-tools.md)",
        "- [HTTP API](http-api.md)",
        "- [Access and mutation policy](access-and-mutation-policy.md)",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the page is stale")
    parser.add_argument("--write", action="store_true", help="regenerate the page")
    args = parser.parse_args()

    rendered = render()

    if args.check:
        if not PAGE.exists():
            print(f"missing: {PAGE}", file=sys.stderr)
            return 1
        if PAGE.read_text() != rendered:
            print(
                f"{PAGE} is stale — the capability registry has moved.\n"
                "Regenerate with: uv run python scripts/development/"
                "generate-capability-matrix.py --write",
                file=sys.stderr,
            )
            return 1
        print("capability matrix is current")
        return 0

    if args.write:
        PAGE.parent.mkdir(parents=True, exist_ok=True)
        PAGE.write_text(rendered)
        print(f"wrote {PAGE} ({len(REGISTRY)} capabilities)")
        return 0

    parser.print_help()
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
