"""Add knowledge chunks with vector embeddings.

Additive over revision 0003 (ADR-0008). One shared chunk table with a single
vector index; knowledge type is a metadata filter, not a separate index.

``knowledge_id`` is ``String(64)`` because revision 0001 created
``knowledge_items.id`` as ``String(64)``, not a UUID column.

Written by hand rather than autogenerated. Autogenerate against CockroachDB
reports cosmetic differences that are not real changes — ``INTEGER`` versus
``BigInteger``, ``VARCHAR`` versus ``Text``, and ``NULLS FIRST`` in reflected
index expressions. Accepting them would rewrite columns that are already correct.

Revision ID: 0004
Revises: 0003
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from kae_memory.persistence import providers
from kae_memory.persistence.providers import ProviderAdapter
from kae_memory.persistence.tables import Vector

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

VECTOR_DIMENSIONS = 1024


def _adapter() -> ProviderAdapter:
    """Return the adapter for the provider this migration is running against.

    Provider-specific DDL is confined to the vector column and its index. The
    relational schema either side of it is identical on both engines, which is
    why there is one migration history rather than two.
    """

    return providers.resolve().adapter


def upgrade() -> None:
    adapter = _adapter()
    for statement in adapter.prepare_statements():
        # pgvector must exist before a vector column can be created. Idempotent,
        # and empty on an engine whose vector support is native.
        op.execute(statement)

    op.create_table(
        "knowledge_chunks",
        sa.Column("chunk_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("project_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("knowledge_id", sa.String(length=64), nullable=False),
        sa.Column("knowledge_kind", sa.String(length=40), nullable=False),
        sa.Column("chunk_index", sa.BigInteger(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(VECTOR_DIMENSIONS), nullable=True),
        sa.Column("embedding_state", sa.String(length=20), nullable=False),
        sa.Column("embedding_model", sa.String(length=120), nullable=True),
        sa.Column("embedding_dimensions", sa.BigInteger(), nullable=True),
        sa.Column("embedding_version", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.project_id"]),
        sa.ForeignKeyConstraint(["knowledge_id"], ["knowledge_items.id"]),
        sa.PrimaryKeyConstraint("chunk_id"),
        sa.UniqueConstraint("knowledge_id", "chunk_index", "embedding_version"),
    )
    op.create_index("ix_knowledge_chunks_knowledge", "knowledge_chunks", ["knowledge_id"])
    op.create_index(
        "ix_knowledge_chunks_project_state", "knowledge_chunks", ["project_id", "embedding_state"]
    )

    # No Alembic operation covers a vector index on either engine, so it is raw
    # DDL from the provider adapter. One index on the shared chunk table — never
    # one per knowledge type (ADR-0008).
    for statement in adapter.create_vector_index(
        "knowledge_chunks", "embedding", providers.VECTOR_INDEX_NAME
    ):
        op.execute(statement)


def downgrade() -> None:
    for statement in _adapter().drop_vector_index("knowledge_chunks", providers.VECTOR_INDEX_NAME):
        op.execute(statement)
    op.drop_index("ix_knowledge_chunks_project_state", table_name="knowledge_chunks")
    op.drop_index("ix_knowledge_chunks_knowledge", table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
