"""Public KAE-Memory domain contracts."""

from .chunks import (
    EMBEDDING_VERSION,
    EmbeddingState,
    KnowledgeChunk,
    content_hash,
    estimate_tokens,
    metadata_prefix,
    split_text,
)
from .errors import (
    DomainError,
    DomainInvariantError,
    InvalidIdentifierError,
    InvalidLifecycleTransitionError,
    InvalidRunTransitionError,
)
from .execution import AgentRole, AgentRun, RunStatus, ensure_run_transition
from .identifiers import (
    AgentId,
    AgentRunId,
    ChunkId,
    ExecutionId,
    KnowledgeItemId,
    MessageId,
    ProjectId,
    ProvenanceLinkId,
    RelationshipId,
    SessionId,
)
from .lifecycle import LifecycleState
from .models import (
    Agent,
    KnowledgeItem,
    KnowledgeKind,
    KnowledgeVersion,
    Project,
    Provenance,
    ProvenanceLink,
    ProvenanceLinkType,
    Relationship,
    RelationshipType,
)
from .workspace import (
    ActorType,
    Message,
    MessageType,
    ProjectStatus,
    Session,
    SessionStatus,
    SessionType,
)

__all__ = [
    "EMBEDDING_VERSION",
    "ActorType",
    "Agent",
    "AgentId",
    "AgentRole",
    "AgentRun",
    "AgentRunId",
    "ChunkId",
    "DomainError",
    "DomainInvariantError",
    "EmbeddingState",
    "ExecutionId",
    "InvalidIdentifierError",
    "InvalidLifecycleTransitionError",
    "InvalidRunTransitionError",
    "KnowledgeChunk",
    "KnowledgeItem",
    "KnowledgeItemId",
    "KnowledgeKind",
    "KnowledgeVersion",
    "LifecycleState",
    "Message",
    "MessageId",
    "MessageType",
    "Project",
    "ProjectId",
    "ProjectStatus",
    "Provenance",
    "ProvenanceLink",
    "ProvenanceLinkId",
    "ProvenanceLinkType",
    "Relationship",
    "RelationshipId",
    "RelationshipType",
    "RunStatus",
    "Session",
    "SessionId",
    "SessionStatus",
    "SessionType",
    "content_hash",
    "ensure_run_transition",
    "estimate_tokens",
    "metadata_prefix",
    "split_text",
]
